// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/posts/post.proto

package onestory_story_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FullPost struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StoryId              int64    `protobuf:"varint,2,opt,name=StoryId,proto3" json:"StoryId,omitempty"`
	PassId               string   `protobuf:"bytes,3,opt,name=PassId,proto3" json:"PassId,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Header               string   `protobuf:"bytes,5,opt,name=Header,proto3" json:"Header,omitempty"`
	Rel                  string   `protobuf:"bytes,6,opt,name=Rel,proto3" json:"Rel,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Ext                  string   `protobuf:"bytes,8,opt,name=Ext,proto3" json:"Ext,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=Update_time,json=UpdateTime,proto3" json:"Update_time,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=Create_time,json=CreateTime,proto3" json:"Create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullPost) Reset()         { *m = FullPost{} }
func (m *FullPost) String() string { return proto.CompactTextString(m) }
func (*FullPost) ProtoMessage()    {}
func (*FullPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{0}
}
func (m *FullPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullPost.Unmarshal(m, b)
}
func (m *FullPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullPost.Marshal(b, m, deterministic)
}
func (dst *FullPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullPost.Merge(dst, src)
}
func (m *FullPost) XXX_Size() int {
	return xxx_messageInfo_FullPost.Size(m)
}
func (m *FullPost) XXX_DiscardUnknown() {
	xxx_messageInfo_FullPost.DiscardUnknown(m)
}

var xxx_messageInfo_FullPost proto.InternalMessageInfo

func (m *FullPost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FullPost) GetStoryId() int64 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *FullPost) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *FullPost) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *FullPost) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *FullPost) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

func (m *FullPost) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FullPost) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *FullPost) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *FullPost) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type SafePost struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StoryId              int64    `protobuf:"varint,2,opt,name=StoryId,proto3" json:"StoryId,omitempty"`
	PassId               string   `protobuf:"bytes,3,opt,name=PassId,proto3" json:"PassId,omitempty"`
	Header               string   `protobuf:"bytes,5,opt,name=Header,proto3" json:"Header,omitempty"`
	Rel                  string   `protobuf:"bytes,6,opt,name=Rel,proto3" json:"Rel,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Ext                  string   `protobuf:"bytes,8,opt,name=Ext,proto3" json:"Ext,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=Update_time,json=UpdateTime,proto3" json:"Update_time,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=Create_time,json=CreateTime,proto3" json:"Create_time,omitempty"`
	CreateDate           int64    `protobuf:"varint,11,opt,name=Create_date,json=CreateDate,proto3" json:"Create_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafePost) Reset()         { *m = SafePost{} }
func (m *SafePost) String() string { return proto.CompactTextString(m) }
func (*SafePost) ProtoMessage()    {}
func (*SafePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{1}
}
func (m *SafePost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafePost.Unmarshal(m, b)
}
func (m *SafePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafePost.Marshal(b, m, deterministic)
}
func (dst *SafePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafePost.Merge(dst, src)
}
func (m *SafePost) XXX_Size() int {
	return xxx_messageInfo_SafePost.Size(m)
}
func (m *SafePost) XXX_DiscardUnknown() {
	xxx_messageInfo_SafePost.DiscardUnknown(m)
}

var xxx_messageInfo_SafePost proto.InternalMessageInfo

func (m *SafePost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SafePost) GetStoryId() int64 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *SafePost) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *SafePost) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *SafePost) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

func (m *SafePost) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SafePost) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *SafePost) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SafePost) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SafePost) GetCreateDate() int64 {
	if m != nil {
		return m.CreateDate
	}
	return 0
}

type RequestQuerySingle struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassId               string   `protobuf:"bytes,2,opt,name=PassId,proto3" json:"PassId,omitempty"`
	StoryId              string   `protobuf:"bytes,3,opt,name=StoryId,proto3" json:"StoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestQuerySingle) Reset()         { *m = RequestQuerySingle{} }
func (m *RequestQuerySingle) String() string { return proto.CompactTextString(m) }
func (*RequestQuerySingle) ProtoMessage()    {}
func (*RequestQuerySingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{2}
}
func (m *RequestQuerySingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestQuerySingle.Unmarshal(m, b)
}
func (m *RequestQuerySingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestQuerySingle.Marshal(b, m, deterministic)
}
func (dst *RequestQuerySingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestQuerySingle.Merge(dst, src)
}
func (m *RequestQuerySingle) XXX_Size() int {
	return xxx_messageInfo_RequestQuerySingle.Size(m)
}
func (m *RequestQuerySingle) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestQuerySingle.DiscardUnknown(m)
}

var xxx_messageInfo_RequestQuerySingle proto.InternalMessageInfo

func (m *RequestQuerySingle) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestQuerySingle) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *RequestQuerySingle) GetStoryId() string {
	if m != nil {
		return m.StoryId
	}
	return ""
}

type RequestQuery struct {
	PassId               string   `protobuf:"bytes,1,opt,name=PassId,proto3" json:"PassId,omitempty"`
	StoryId              int64    `protobuf:"varint,2,opt,name=StoryId,proto3" json:"StoryId,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	IsDesc               bool     `protobuf:"varint,5,opt,name=isDesc,proto3" json:"isDesc,omitempty"`
	Limit                int64    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestQuery) Reset()         { *m = RequestQuery{} }
func (m *RequestQuery) String() string { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()    {}
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{3}
}
func (m *RequestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestQuery.Unmarshal(m, b)
}
func (m *RequestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestQuery.Marshal(b, m, deterministic)
}
func (dst *RequestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestQuery.Merge(dst, src)
}
func (m *RequestQuery) XXX_Size() int {
	return xxx_messageInfo_RequestQuery.Size(m)
}
func (m *RequestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestQuery proto.InternalMessageInfo

func (m *RequestQuery) GetPassId() string {
	if m != nil {
		return m.PassId
	}
	return ""
}

func (m *RequestQuery) GetStoryId() int64 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *RequestQuery) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RequestQuery) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RequestQuery) GetIsDesc() bool {
	if m != nil {
		return m.IsDesc
	}
	return false
}

func (m *RequestQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Request struct {
	Info                 *FullPost `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{4}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInfo() *FullPost {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{5}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResponseList struct {
	Code                 int64       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	List                 []*SafePost `protobuf:"bytes,3,rep,name=List,proto3" json:"List,omitempty"`
	Limit                int64       `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64       `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResponseList) Reset()         { *m = ResponseList{} }
func (m *ResponseList) String() string { return proto.CompactTextString(m) }
func (*ResponseList) ProtoMessage()    {}
func (*ResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{6}
}
func (m *ResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseList.Unmarshal(m, b)
}
func (m *ResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseList.Marshal(b, m, deterministic)
}
func (dst *ResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseList.Merge(dst, src)
}
func (m *ResponseList) XXX_Size() int {
	return xxx_messageInfo_ResponseList.Size(m)
}
func (m *ResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseList proto.InternalMessageInfo

func (m *ResponseList) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseList) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseList) GetList() []*SafePost {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ResponseList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ResponseList) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ResponseSafe struct {
	Code                 int64     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *SafePost `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseSafe) Reset()         { *m = ResponseSafe{} }
func (m *ResponseSafe) String() string { return proto.CompactTextString(m) }
func (*ResponseSafe) ProtoMessage()    {}
func (*ResponseSafe) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_af527ecd001bbd93, []int{7}
}
func (m *ResponseSafe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSafe.Unmarshal(m, b)
}
func (m *ResponseSafe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSafe.Marshal(b, m, deterministic)
}
func (dst *ResponseSafe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSafe.Merge(dst, src)
}
func (m *ResponseSafe) XXX_Size() int {
	return xxx_messageInfo_ResponseSafe.Size(m)
}
func (m *ResponseSafe) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSafe.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSafe proto.InternalMessageInfo

func (m *ResponseSafe) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseSafe) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseSafe) GetData() *SafePost {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*FullPost)(nil), "onestory.story.proto.FullPost")
	proto.RegisterType((*SafePost)(nil), "onestory.story.proto.SafePost")
	proto.RegisterType((*RequestQuerySingle)(nil), "onestory.story.proto.RequestQuerySingle")
	proto.RegisterType((*RequestQuery)(nil), "onestory.story.proto.RequestQuery")
	proto.RegisterType((*Request)(nil), "onestory.story.proto.Request")
	proto.RegisterType((*Response)(nil), "onestory.story.proto.Response")
	proto.RegisterType((*ResponseList)(nil), "onestory.story.proto.ResponseList")
	proto.RegisterType((*ResponseSafe)(nil), "onestory.story.proto.ResponseSafe")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	InsertPostsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseSafe, error)
	UpdatePostsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetPostsList(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseList, error)
	GetPostById(ctx context.Context, in *RequestQuerySingle, opts ...grpc.CallOption) (*ResponseSafe, error)
}

type postsServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostsServiceClient(cc *grpc.ClientConn) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) InsertPostsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseSafe, error) {
	out := new(ResponseSafe)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.PostsService/InsertPostsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePostsInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.PostsService/UpdatePostsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostsList(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseList, error) {
	out := new(ResponseList)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.PostsService/GetPostsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostById(ctx context.Context, in *RequestQuerySingle, opts ...grpc.CallOption) (*ResponseSafe, error) {
	out := new(ResponseSafe)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.PostsService/GetPostById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	InsertPostsInfo(context.Context, *Request) (*ResponseSafe, error)
	UpdatePostsInfo(context.Context, *Request) (*Response, error)
	GetPostsList(context.Context, *RequestQuery) (*ResponseList, error)
	GetPostById(context.Context, *RequestQuerySingle) (*ResponseSafe, error)
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_InsertPostsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).InsertPostsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.PostsService/InsertPostsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).InsertPostsInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePostsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePostsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.PostsService/UpdatePostsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePostsInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.PostsService/GetPostsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostsList(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuerySingle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.PostsService/GetPostById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostById(ctx, req.(*RequestQuerySingle))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onestory.story.proto.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertPostsInfo",
			Handler:    _PostsService_InsertPostsInfo_Handler,
		},
		{
			MethodName: "UpdatePostsInfo",
			Handler:    _PostsService_UpdatePostsInfo_Handler,
		},
		{
			MethodName: "GetPostsList",
			Handler:    _PostsService_GetPostsList_Handler,
		},
		{
			MethodName: "GetPostById",
			Handler:    _PostsService_GetPostById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/posts/post.proto",
}

func init() { proto.RegisterFile("grpc/proto/posts/post.proto", fileDescriptor_post_af527ecd001bbd93) }

var fileDescriptor_post_af527ecd001bbd93 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0xb4, 0x49, 0x26, 0x11, 0x45, 0xab, 0x0a, 0xad, 0xf8, 0x28, 0xd1, 0x9e, 0x72,
	0x4a, 0xa5, 0x70, 0xe6, 0x42, 0x52, 0xc0, 0x52, 0x91, 0xca, 0x86, 0x56, 0x5c, 0x10, 0x32, 0xf1,
	0x34, 0xb2, 0x94, 0xd8, 0xc6, 0xbb, 0x41, 0xed, 0x0f, 0xe0, 0x4f, 0xf0, 0x53, 0xf8, 0x5b, 0x48,
	0x9c, 0xd1, 0xcc, 0xda, 0x8d, 0x81, 0xa4, 0x4d, 0x25, 0x0e, 0x5c, 0xa2, 0x7d, 0xcf, 0x6f, 0xdf,
	0xce, 0xbc, 0xc9, 0xc0, 0xa3, 0x59, 0x91, 0x4f, 0x8f, 0xf2, 0x22, 0xb3, 0xd9, 0x51, 0x9e, 0x19,
	0x6b, 0xf8, 0x77, 0xc0, 0x84, 0x38, 0xc8, 0x52, 0x34, 0x36, 0x2b, 0xae, 0x06, 0xee, 0x97, 0x59,
	0xf5, 0xd3, 0x83, 0xd6, 0xcb, 0xe5, 0x7c, 0x7e, 0x9a, 0x19, 0x2b, 0xee, 0x81, 0x1f, 0xc6, 0xd2,
	0xeb, 0x79, 0xfd, 0x40, 0xfb, 0x61, 0x2c, 0x24, 0x34, 0x27, 0xa4, 0x0d, 0x63, 0xe9, 0x33, 0x59,
	0x41, 0xf1, 0x00, 0xf6, 0x4e, 0x23, 0x63, 0xc2, 0x58, 0x06, 0x3d, 0xaf, 0xdf, 0xd6, 0x25, 0x12,
	0xf7, 0x21, 0x38, 0x4b, 0x62, 0xd9, 0x60, 0x35, 0x1d, 0x49, 0xf9, 0x1a, 0xa3, 0x18, 0x0b, 0xb9,
	0xeb, 0x94, 0x0e, 0x91, 0x52, 0xe3, 0x5c, 0xee, 0x31, 0x49, 0x47, 0x7a, 0x6d, 0x94, 0xa5, 0x16,
	0x53, 0x2b, 0x9b, 0xcc, 0x56, 0x90, 0xb4, 0xc7, 0x97, 0x56, 0xb6, 0x9c, 0xf6, 0xf8, 0xd2, 0x8a,
	0xa7, 0xd0, 0x39, 0xcb, 0xe3, 0xc8, 0xe2, 0x47, 0x9b, 0x2c, 0x50, 0xb6, 0xf9, 0x3d, 0x70, 0xd4,
	0xbb, 0x64, 0x81, 0x24, 0x18, 0x15, 0x78, 0x2d, 0x00, 0x27, 0x70, 0x14, 0x09, 0xd4, 0x57, 0x1f,
	0x5a, 0x93, 0xe8, 0x02, 0xff, 0x51, 0xe3, 0xff, 0x69, 0x9b, 0x35, 0x01, 0xdd, 0x91, 0x9d, 0xba,
	0x60, 0x1c, 0x59, 0x54, 0xe7, 0x20, 0x34, 0x7e, 0x5e, 0xa2, 0xb1, 0x6f, 0x97, 0x58, 0x5c, 0x4d,
	0x92, 0x74, 0x36, 0xc7, 0xbf, 0x02, 0x59, 0xb5, 0xed, 0xff, 0xd6, 0x76, 0x2d, 0x28, 0x97, 0x47,
	0x05, 0xd5, 0x77, 0x0f, 0xba, 0x75, 0xe3, 0x9a, 0x85, 0xb7, 0xc9, 0xe2, 0x8f, 0xac, 0x1f, 0x43,
	0xdb, 0xd8, 0xa8, 0xb0, 0xd4, 0x08, 0xdb, 0x07, 0x7a, 0x45, 0xd0, 0x3d, 0x4c, 0x63, 0xfe, 0xe6,
	0xfe, 0x6e, 0x15, 0xa4, 0x97, 0x12, 0x33, 0x46, 0x33, 0xe5, 0x59, 0xb4, 0x74, 0x89, 0xc4, 0x01,
	0xec, 0xce, 0x93, 0x45, 0x62, 0x79, 0x1a, 0x81, 0x76, 0x40, 0x08, 0x68, 0xe4, 0xd1, 0x0c, 0x79,
	0x18, 0x81, 0xe6, 0xb3, 0x7a, 0x0e, 0xcd, 0xb2, 0x76, 0x31, 0x84, 0x46, 0x98, 0x5e, 0x64, 0x5c,
	0x74, 0x67, 0x78, 0x38, 0x58, 0xb7, 0x45, 0x83, 0x6a, 0x83, 0x34, 0x6b, 0xd5, 0x09, 0xb4, 0x34,
	0x9a, 0x3c, 0x4b, 0x0d, 0x92, 0xfd, 0x28, 0x8b, 0xb1, 0xcc, 0x92, 0xcf, 0x54, 0xfa, 0x1b, 0x34,
	0x86, 0x5e, 0x75, 0x71, 0x56, 0x90, 0xd4, 0xe3, 0xc8, 0x46, 0x65, 0x98, 0x7c, 0x56, 0xdf, 0x38,
	0x49, 0x67, 0x77, 0x92, 0x18, 0x7b, 0x47, 0xcb, 0x21, 0x34, 0xe8, 0x96, 0x0c, 0x7a, 0xc1, 0xe6,
	0x06, 0xaa, 0x4d, 0xd0, 0xac, 0x5d, 0x25, 0xd5, 0x58, 0x97, 0xd4, 0x6e, 0x2d, 0xa9, 0x7c, 0x55,
	0x1b, 0x79, 0xdc, 0xbd, 0xb6, 0xeb, 0x76, 0xb7, 0xa8, 0x8d, 0xb4, 0xc3, 0x1f, 0x3e, 0x74, 0x09,
	0x9a, 0x09, 0x16, 0x5f, 0x92, 0x29, 0x8a, 0x73, 0xd8, 0x0f, 0x53, 0x83, 0x85, 0x65, 0x96, 0x06,
	0x20, 0x9e, 0xac, 0x77, 0x2a, 0x67, 0xfa, 0x50, 0x6d, 0xfa, 0xbc, 0x6a, 0x44, 0xed, 0x08, 0x0d,
	0xfb, 0x6e, 0xd3, 0xb6, 0xf6, 0x3d, 0xbc, 0xd9, 0x57, 0xed, 0x88, 0xf7, 0xd0, 0x7d, 0x85, 0xae,
	0x50, 0x0e, 0x5a, 0xdd, 0x68, 0xc8, 0x8b, 0x73, 0x5b, 0xb5, 0xe4, 0xa3, 0x76, 0xc4, 0x07, 0xe8,
	0x94, 0xce, 0x2f, 0x68, 0x77, 0xfa, 0xb7, 0x1b, 0xbb, 0x55, 0xdf, 0x2e, 0x8c, 0x4f, 0x7b, 0xcc,
	0x3e, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x90, 0x6e, 0x84, 0x63, 0x06, 0x00, 0x00,
}
