// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/story/story.proto

package onestory_story_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoryInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StoryId              int64    `protobuf:"varint,2,opt,name=StoryId,proto3" json:"StoryId,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=Cover,proto3" json:"Cover,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=Desc,proto3" json:"Desc,omitempty"`
	PenName              string   `protobuf:"bytes,7,opt,name=PenName,proto3" json:"PenName,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	IsOpen               int32    `protobuf:"varint,10,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`
	Extend               string   `protobuf:"bytes,11,opt,name=Extend,proto3" json:"Extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoryInfo) Reset()         { *m = StoryInfo{} }
func (m *StoryInfo) String() string { return proto.CompactTextString(m) }
func (*StoryInfo) ProtoMessage()    {}
func (*StoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_story_4034f4c1cc2eb28a, []int{0}
}
func (m *StoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoryInfo.Unmarshal(m, b)
}
func (m *StoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoryInfo.Marshal(b, m, deterministic)
}
func (dst *StoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoryInfo.Merge(dst, src)
}
func (m *StoryInfo) XXX_Size() int {
	return xxx_messageInfo_StoryInfo.Size(m)
}
func (m *StoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StoryInfo proto.InternalMessageInfo

func (m *StoryInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoryInfo) GetStoryId() int64 {
	if m != nil {
		return m.StoryId
	}
	return 0
}

func (m *StoryInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StoryInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *StoryInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StoryInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *StoryInfo) GetPenName() string {
	if m != nil {
		return m.PenName
	}
	return ""
}

func (m *StoryInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *StoryInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *StoryInfo) GetIsOpen() int32 {
	if m != nil {
		return m.IsOpen
	}
	return 0
}

func (m *StoryInfo) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

type RequestStoryId struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	StoryId              []int64  `protobuf:"varint,2,rep,packed,name=StoryId,proto3" json:"StoryId,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStoryId) Reset()         { *m = RequestStoryId{} }
func (m *RequestStoryId) String() string { return proto.CompactTextString(m) }
func (*RequestStoryId) ProtoMessage()    {}
func (*RequestStoryId) Descriptor() ([]byte, []int) {
	return fileDescriptor_story_4034f4c1cc2eb28a, []int{1}
}
func (m *RequestStoryId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStoryId.Unmarshal(m, b)
}
func (m *RequestStoryId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStoryId.Marshal(b, m, deterministic)
}
func (dst *RequestStoryId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStoryId.Merge(dst, src)
}
func (m *RequestStoryId) XXX_Size() int {
	return xxx_messageInfo_RequestStoryId.Size(m)
}
func (m *RequestStoryId) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStoryId.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStoryId proto.InternalMessageInfo

func (m *RequestStoryId) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RequestStoryId) GetStoryId() []int64 {
	if m != nil {
		return m.StoryId
	}
	return nil
}

func (m *RequestStoryId) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_story_4034f4c1cc2eb28a, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResponseStoryList struct {
	Code                 int64        `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	StoryList            []*StoryInfo `protobuf:"bytes,3,rep,name=StoryList,proto3" json:"StoryList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResponseStoryList) Reset()         { *m = ResponseStoryList{} }
func (m *ResponseStoryList) String() string { return proto.CompactTextString(m) }
func (*ResponseStoryList) ProtoMessage()    {}
func (*ResponseStoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_story_4034f4c1cc2eb28a, []int{3}
}
func (m *ResponseStoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStoryList.Unmarshal(m, b)
}
func (m *ResponseStoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStoryList.Marshal(b, m, deterministic)
}
func (dst *ResponseStoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStoryList.Merge(dst, src)
}
func (m *ResponseStoryList) XXX_Size() int {
	return xxx_messageInfo_ResponseStoryList.Size(m)
}
func (m *ResponseStoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStoryList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStoryList proto.InternalMessageInfo

func (m *ResponseStoryList) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseStoryList) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseStoryList) GetStoryList() []*StoryInfo {
	if m != nil {
		return m.StoryList
	}
	return nil
}

func init() {
	proto.RegisterType((*StoryInfo)(nil), "onestory.story.proto.StoryInfo")
	proto.RegisterType((*RequestStoryId)(nil), "onestory.story.proto.RequestStoryId")
	proto.RegisterType((*Response)(nil), "onestory.story.proto.Response")
	proto.RegisterType((*ResponseStoryList)(nil), "onestory.story.proto.ResponseStoryList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoryServiceClient is the client API for StoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoryServiceClient interface {
	CreateStory(ctx context.Context, in *StoryInfo, opts ...grpc.CallOption) (*Response, error)
	GetStoryList(ctx context.Context, in *RequestStoryId, opts ...grpc.CallOption) (*ResponseStoryList, error)
	UpdateStory(ctx context.Context, in *StoryInfo, opts ...grpc.CallOption) (*Response, error)
}

type storyServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoryServiceClient(cc *grpc.ClientConn) StoryServiceClient {
	return &storyServiceClient{cc}
}

func (c *storyServiceClient) CreateStory(ctx context.Context, in *StoryInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.StoryService/CreateStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetStoryList(ctx context.Context, in *RequestStoryId, opts ...grpc.CallOption) (*ResponseStoryList, error) {
	out := new(ResponseStoryList)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.StoryService/GetStoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) UpdateStory(ctx context.Context, in *StoryInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/onestory.story.proto.StoryService/UpdateStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServiceServer is the server API for StoryService service.
type StoryServiceServer interface {
	CreateStory(context.Context, *StoryInfo) (*Response, error)
	GetStoryList(context.Context, *RequestStoryId) (*ResponseStoryList, error)
	UpdateStory(context.Context, *StoryInfo) (*Response, error)
}

func RegisterStoryServiceServer(s *grpc.Server, srv StoryServiceServer) {
	s.RegisterService(&_StoryService_serviceDesc, srv)
}

func _StoryService_CreateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).CreateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.StoryService/CreateStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).CreateStory(ctx, req.(*StoryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetStoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).GetStoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.StoryService/GetStoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).GetStoryList(ctx, req.(*RequestStoryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_UpdateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).UpdateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onestory.story.proto.StoryService/UpdateStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).UpdateStory(ctx, req.(*StoryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onestory.story.proto.StoryService",
	HandlerType: (*StoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStory",
			Handler:    _StoryService_CreateStory_Handler,
		},
		{
			MethodName: "GetStoryList",
			Handler:    _StoryService_GetStoryList_Handler,
		},
		{
			MethodName: "UpdateStory",
			Handler:    _StoryService_UpdateStory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/story/story.proto",
}

func init() { proto.RegisterFile("grpc/proto/story/story.proto", fileDescriptor_story_4034f4c1cc2eb28a) }

var fileDescriptor_story_4034f4c1cc2eb28a = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x8b, 0xda, 0x40,
	0x14, 0xc5, 0x4d, 0xe2, 0xbf, 0x5c, 0x45, 0xda, 0x41, 0xca, 0x20, 0xc5, 0x86, 0x50, 0x68, 0x9e,
	0x14, 0xec, 0x73, 0x9f, 0x6c, 0x29, 0x01, 0xdb, 0x4a, 0xd4, 0xe7, 0x92, 0x9a, 0x5b, 0x09, 0xd4,
	0x4c, 0x9a, 0x99, 0x4a, 0xf7, 0x6d, 0xbf, 0xc2, 0xb2, 0x5f, 0x78, 0x99, 0x3b, 0x19, 0xf5, 0xc1,
	0x75, 0x59, 0xd8, 0x97, 0x70, 0xcf, 0xef, 0x66, 0xce, 0xcc, 0x3d, 0x33, 0xf0, 0x76, 0x57, 0x95,
	0xdb, 0x69, 0x59, 0x09, 0x25, 0xa6, 0x52, 0x89, 0xea, 0xc6, 0x7c, 0x27, 0x44, 0xd8, 0x50, 0x14,
	0x68, 0xf4, 0x19, 0x0d, 0xef, 0x5c, 0xf0, 0x57, 0x5a, 0xc7, 0xc5, 0x6f, 0xc1, 0x06, 0xe0, 0xc6,
	0x19, 0x77, 0x02, 0x27, 0xf2, 0x12, 0x37, 0xce, 0x18, 0x87, 0x8e, 0x69, 0x66, 0xdc, 0x25, 0x68,
	0x25, 0x7b, 0x05, 0xde, 0x26, 0xcf, 0xb8, 0x17, 0x38, 0x91, 0x9f, 0xe8, 0x92, 0x0d, 0xa1, 0x35,
	0x17, 0x07, 0xac, 0x78, 0x93, 0x98, 0x11, 0x9a, 0xae, 0x73, 0xf5, 0x07, 0x79, 0xcb, 0x50, 0x12,
	0x8c, 0x41, 0xf3, 0x33, 0xca, 0x2d, 0x6f, 0x13, 0xa4, 0x5a, 0xef, 0xb5, 0xc4, 0xe2, 0x7b, 0xba,
	0x47, 0xde, 0x21, 0x6c, 0x25, 0x1b, 0x03, 0xcc, 0x2b, 0x4c, 0x15, 0xae, 0xf3, 0x3d, 0xf2, 0x2e,
	0x1d, 0xe4, 0x8c, 0xe8, 0xfe, 0xa6, 0xcc, 0x6c, 0xdf, 0x37, 0xfd, 0x13, 0x61, 0x6f, 0xa0, 0x1d,
	0xcb, 0x1f, 0x25, 0x16, 0x1c, 0x02, 0x27, 0x6a, 0x25, 0xb5, 0xd2, 0xfc, 0xcb, 0x7f, 0x85, 0x45,
	0xc6, 0x7b, 0xb4, 0x61, 0xad, 0xc2, 0x05, 0x0c, 0x12, 0xfc, 0xfb, 0x0f, 0xa5, 0xb2, 0xd3, 0xda,
	0x5c, 0xbc, 0x4b, 0xb9, 0x78, 0x57, 0x73, 0x09, 0x17, 0xd0, 0x4d, 0x50, 0x96, 0xa2, 0x90, 0x34,
	0xf7, 0x5c, 0x64, 0x58, 0x27, 0x4c, 0xb5, 0xf6, 0xfa, 0x86, 0x52, 0xa6, 0x3b, 0xa4, 0x8c, 0xfd,
	0xc4, 0x4a, 0x4a, 0x29, 0x55, 0x69, 0x6d, 0x46, 0x75, 0x78, 0xeb, 0xc0, 0x6b, 0x6b, 0x47, 0x7b,
	0x2e, 0x72, 0xa9, 0x9e, 0xe9, 0xfb, 0xa9, 0xbe, 0x72, 0xbd, 0x94, 0x7b, 0x81, 0x17, 0xf5, 0x66,
	0xef, 0x26, 0x97, 0x5e, 0xc7, 0xe4, 0xf8, 0x32, 0x92, 0xd3, 0x8a, 0xd9, 0xbd, 0x0b, 0x7d, 0x52,
	0x2b, 0xac, 0x0e, 0xf9, 0x16, 0xd9, 0x12, 0x7a, 0xe6, 0x36, 0x88, 0xb2, 0xa7, 0xbc, 0x46, 0xe3,
	0xcb, 0x3f, 0xd8, 0xb1, 0xc2, 0x06, 0xfb, 0x09, 0xfd, 0xaf, 0xa8, 0x4e, 0xf3, 0xbd, 0x7f, 0x6c,
	0xc5, 0xf9, 0x2d, 0x8d, 0x3e, 0x5c, 0xf7, 0x3d, 0xda, 0x85, 0x0d, 0x7d, 0x64, 0xf3, 0x40, 0x5e,
	0xea, 0xc8, 0xbf, 0xda, 0x44, 0x3e, 0x3e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x32, 0x29, 0x07, 0x2f,
	0x85, 0x03, 0x00, 0x00,
}
